CREATE TYPE IF NOT EXISTS ITEM_TYPE AS ENUM ('ARTICLE', 'VIDEO', 'PODCAST');

CREATE TABLE IF NOT EXISTS items (
    ID SERIAL PRIMARY KEY,

    USER_ID INT NOT NULL,
    TYPE ITEM_TYPE NOT NULL,

    URL STRING NOT NULL,
    TITLE VARCHAR(500) NOT NULL,
    IMAGE BYTES NOT NULL,

    ADDED_TIMESTAMP TIMESTAMPTZ NOT NULL,
    UNIQUE INDEX url_key (URL)
);

CREATE INDEX IF NOT EXISTS user_id_idx ON items (USER_ID)
