########################
# Spring boot properties
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
########################
server:
  port: 9090
---
spring:
  output:
    ansi:
      enabled: ALWAYS

  profiles:
    include: data

  jpa:
    open-in-view: false
---
spring:
  profiles: prod
server:
  port: 8080
---
management:
  endpoints:
    web:
      exposure:
        include: conditions,env,info,health,httptrace,metrics,threaddump,shutdown,configprops,liquibase
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true

